user:
    resource: "@UserBundle/Controller/"
    type:     annotation

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:  { _controller: UserBundle:Auth:login }
login_check:
    path: /login-check
logout:
    path: /logout